language: python
python:
  - "2.7"

env:
  # the 'relengapi' command wants a settings file, but the contents
  # aren't terribly important, so the example will do fine.  This is
  # relative to the directory containing app.py, although Flask does not
  # document that.
  - RELENGAPI_SETTINGS=../settings_example.py

# command to install dependencies
install:
  - ./install_relengapi.sh
  - "pip install coverage"
  - "pip install coveralls"
  - "pip freeze"

# run everything in a single script, so we get a nice summary at the end
script:
  - bash ./validate.sh

after_success:
  - coveralls --rcfile coveragerc

# currently cannot customise per user fork, see:
# https://github.com/travis-ci/travis-ci/issues/1094
# please comment out this section in your personal fork!
notifications:
  irc:
    channels:
      - "irc.mozilla.org#callek"
    on_success: always
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Commit message : %{commit_message}"
